project:
  type: website
  render:
  - "index.qmd"
  - "*.Rmd"
  - "*.md"
           

website:
  title: "CDABS Intro to Programming"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:shell
      - sidebar:r
      - sidebar:python

  sidebar:
    - id: shell
      title: "Shell"
      style: "docked"
      background: light
      collapse-level: 2
      contents:
      - "shell_lesson/01-introduction.md"
      - "shell_lesson/02-the-filesystem.md"
      - "shell_lesson/04-redirection.md"
      - "shell_lesson/05-writing-scripts.md"
      - "shell_lesson/06-organization.md"

    - id: r
      title: "R"
      contents: r_lesson/*.Rmd
        
    - id: python
      title: "Python"
      contents: python_lesson/*.md

format:
  html:
    theme: yeti
    editor: source
    toc: true



