project:
  type: website
  render:
  - "index.qmd"
  - "*.md"
           

website:
  title: "CDABS Intro to Programming"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:shell
      - sidebar:r
      - sidebar:python

  sidebar:
    - id: shell
      title: "Shell"
      style: "docked"
      background: light
      collapse-level: 2
      contents: shell/*.md
        
        
    - id: r
      title: "R"
      contents: r/*.md
        
    - id: python
      title: "Python"
      contents: python/*.md

format:
  html:
    theme: yeti
    editor: source
    toc: true



