project:
  type: website

website:
  title: "CDABS Intro to Programming"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: 01-introduction.md
        text: Shell
      
      

format:
  html:
    theme: yeti
    editor: source
    toc: true



