---
title: "Intro to Programming"
author: "Amy Yarnell, Irmarie Fraticelli-Rodriguez"
title-block-banner: white
title-block-banner-color: black
navbar:
    page-navigation: true
format: 
  html:
    embed-resources: true
toc: true
editor: source
css: styles.css
---

## Course Description: 

*Intro to the shell*
In this lesson, you will be learning about the command line, also known as the shell, terminal, bash, etc. You will learn concepts essential for using the command line for bioinformatics, such as navigating the file system, computationally manipulating your files (including copying, moving, and renaming), searching files, redirecting output, and writing shell scripts.
  
*Intro to R and RStudio*
In this lesson, you will be learning about R and how it is used for data science and bioinformatics. You will learn about R syntax, data types, and how to set up and use RStudio – a powerful and convenient environment in which to work with R. You will also be introduced to the popular Tidyverse collection of packages for data wrangling and visualization.

*Intro to Python*
In this lesson, you will be learning about Python and how it is used for data science and bioinformatics. You will learn Python syntax and package management, using both a text editor and Jupyter notebooks to write and execute Python code. 

**Schedule**

| Date | Topic                     |
|------|---------------------------|
| October 5th, 2023    | Intro to the Command Line |
| October 12th, 2023   | R and RStudio             |
| October 19th, 2023   | Python                    |

## Resources

This material was lightly adapted from the [Data Carpentry Genomics Curriculum](https://datacarpentry.org/lessons/#genomics-workshop) which is shared under a [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/) license.


